### PR TITLE
L4T R32.7.3 updates for kirkstone

### LINKED ISSUE #1121: L4T 32.7.3 BSP update request
Hi,

This isn't an issue but more of a question: is the L4T 32.7.3 release support on the roadmap for meta-tegra?

Thank you

### PR DESCRIPTION
**Pull request by madisongh**
Notes

* Until NVIDIA republishes the L4T R32.7.3 BSP packages for anonymous access, you'll have to manually download the packages via SDK Manager or through a web browser and pre-load your DL_DIR with them.  Will hold off on converting this to a real PR until NVIDIA fixes the issue.
* Linux kernel is now 4.9.299-based.  New branch has been pushed to the kernel repo.
* TensorRT deb packages got republished with new SHAs, but are the exact same versions (and file names) as before.

Have run the following tests with demo-image-full images on these platforms, all successfully:
* jetson-agx-xavier-devkit: gstreamer, MMAPI, TensorRT, VPI
* jeston-xavier-nx-devkit-emmc: gstreamer, MMAPI, TensorRT, VPI
* jetson-xavier-nx-devkit-tx2-nx: gstreamer, MMAPI, TensorRT, VPI, Mender
* jetson-nano-devkit-emmc: gstreamer, MMAPI, VPI, Mender

If anyone can help with running more tests (e.g., container support, Wayland/Weston) and covering other dev kits, that would be helpful.  Please make a note here or mention it on the Gitter channel.

TBD:
* The meta-mender-tegra layer in meta-mender-community needs updating (symlinks for the new L4T version in appropriate places).  For the testing I mentioned above, I manually hacked the symlinks in my build workspace.
* Looks like we also need to update meta-mender-tegra's kirkstone branch with the updated u-boot patches we have in under meta-tegra-community/dynamic-layers/meta-mender-tegra ?

Fixes #1121

### CODE REVIEW

**Comment by dwalkes** [comment]
Thanks @madisongh I'll see if I can get a TX2 devkit build going and also look into the mender issues you mentioned.

**Comment by dwalkes** [comment]
For anyone else trying to setup their download directory, here’s what I did for a successful build of `demo-image-full` with TX2 on https://github.com/Trellis-Logic/tegra-demo-distro/tree/wip-kirkstone-l4t-r32.7.3
1. Ran SDK manager and got through the setup step, then copied the content from `~/nvidia_sdk/JetPack_4.6.3_Linux_JETSON_TX2_TARGETS/Linux_for_Tegra/nv_tegra/l4t_deb_packages` to the `build/downloads` subdirectory (or whatever you have setup as `DL_DIR`
2. Downloaded several packages from https://developer.nvidia.com/embedded/linux-tegra-r3273, renamed and copied to `DL_DIR`
  * Driver Package BSP Sources - saved as Jetson-public_sources-32.7.3.tbz2 and then copied to `DL_DIR`
  * Fuse Burning and Secure Boot Documentation and Tools - saved as Jetson_secureboot_32.7.3.tbz2 and copied to `DL_DIR`
  * CBoot sources - saved as `cboot_src_t18x-32.7.3.tbz2` and copied to  `DL_DIR` (Use t194 instead of t18x if you download the 194 sources.. append the -32.7.3)

**Comment by dwalkes** [comment]
Started gitter channel for testing at https://gitter.im/OE4T/jetpack-4.6.3-test

**Comment by madisongh** [comment]
> Looks like this also affects the current kirkstone kirkstone-l4t-r32.7.x branch I tried to include the tensorrt packages and do receive a lot of checksum mismatch errors

Yes, unfortunately, all the 32.7.x-based  branches will need to have the tensorrt checksums fixed.

**Comment by ichergui** [comment]
> > Looks like this also affects the current kirkstone kirkstone-l4t-r32.7.x branch I tried to include the tensorrt packages and do receive a lot of checksum mismatch errors
> 
> Yes, unfortunately, all the 32.7.x-based branches will need to have the tensorrt checksums fixed.

I can fix later today :wink:

**Comment by graugans** [comment]
> > > Looks like this also affects the current kirkstone kirkstone-l4t-r32.7.x branch I tried to include the tensorrt packages and do receive a lot of checksum mismatch errors
> > 
> > 
> > Yes, unfortunately, all the 32.7.x-based branches will need to have the tensorrt checksums fixed.
> 
> I can fix later today 😉

No hurry from my side, I have fixed it in our application layer. I have to fix the layer anyways for now because when this gets merged we have to forward port our kernel patches anyway.

I thought of a merge request from myself but I do not have the possibility to test for all configurations and packages at the moment.

**Pull request merged**
