### PR TITLE
tegra234.inc: no need to add nvidia-drm and nvidia-modeset to the

### PR DESCRIPTION
**Pull request by ichergui**
KERNEL_MODULE_AUTOLOAD list.

This fixes the following issue

[    44.378] (II) NVIDIA(0): NVIDIA GPU Orin (nvgpu) (GA10B) at SoC (GPU-0)
[    44.378] (--) NVIDIA(0): Memory: 31269432 kBytes
[    44.378] (--) NVIDIA(0): VideoBIOS:
[    44.378] (EE) NVIDIA(GPU-0): Failed to acquire modesetting permission.
[    44.378] (EE) NVIDIA(0): Failing initialization of X screen

Signed-off-by: Ilies CHERGUI <ilies.chergui@gmail.com>

### CODE REVIEW

**Comment by ichergui** [comment]
* This patch was tested on `Jetson Orin AGX` with the following image:
* `demo-image-sato` 
* `demo-image-full`
Both work fine

IMG-1791

**Comment by ichergui** [comment]
Can anyone please try `demo-image-weston` image ?

**Review by kekiefer — CHANGES_REQUESTED** [review]
I think we should leave the `KERNEL_MODULE_AUTOLOAD` alone, regardless, as this doesn't hurt x11.

The question is about adding the `modeset=1` to `nvidia-drm`. Perhaps we could only choose to remove this from `KERNEL_MODULE_PROBECONF` if we have a distro features setup with `x11` and not `wayland`?

**Comment by ichergui** [comment]
> I think we should leave the `KERNEL_MODULE_AUTOLOAD` alone, regardless, as this doesn't hurt x11.
> 
> The question is about adding the `modeset=1` to `nvidia-drm`. Perhaps we could only choose to remove this from `KERNEL_MODULE_PROBECONF` if we have a distro features setup with `x11` and not `wayland`?

Our distro features have both `X11` and `Wayland`

**Comment by madisongh** [comment]
> > I think we should leave the `KERNEL_MODULE_AUTOLOAD` alone, regardless, as this doesn't hurt x11.
> > The question is about adding the `modeset=1` to `nvidia-drm`. Perhaps we could only choose to remove this from `KERNEL_MODULE_PROBECONF` if we have a distro features setup with `x11` and not `wayland`?
> 
> Our distro features have both `X11` and `Wayland`

But @kekiefer 's comment still stands.  Can you leave the modules in `KERNEL_MODULE_AUTOLOAD` and just use  the recipe to do the `nvidia-drm modeset=1` probeconf file?

**Comment by madisongh** [comment]
I've merged manually with the changes suggested above.

**Pull request closed without merging**
