### PR TITLE
recipes-bsp/uefi: make UefiUpdateSecurityKeys optional

### PR DESCRIPTION
**Pull request by Lexmark-chad**
I took a stab at making this optional.  It builds with a db key and cert locally defined, but it is untested as I'm not quite setup to test that yet.

### CODE REVIEW

**Comment by Lexmark-chad** [comment]
I think there is more work to do here.  I see that `tegra_bootcontrol_overlay_list` was recently re-worked and I think there is more cleanup that can be done.

**Comment by Lexmark-chad** [comment]
I think this is ready for review now.

**Comment by ichergui** [comment]
I will review it and will share my thoughts

**Comment by madisongh** [comment]
I have manually merged this with a small tweak to the overlay inclusion logic in image_types_tegra so the update key overlay still only gets included for update payloads.

**Comment by madisongh** [comment]
Thanks, @Lexmark-chad !

**Pull request closed without merging**
