### PR TITLE
L4T R35.6.0 update for scarthgap-l4t-r35.x branch

### PR DESCRIPTION
**Pull request by madisongh**
* All BSP recipes updated, except UEFI (waiting on updated sources in the github repos)
* Basic flash and boot tests with
    - AGX Orin devkit - demo-image-base
    - p3768-0000-p3767-0000 - demo-image-weston

Update 2024-09-24:
* The R35.6 UEFI sources have been updated in Github, so the recipes are now updated
* Rebased onto latest `scarthgap-l4t-r35.x`

### CODE REVIEW

**Comment by dwalkes** [comment]
Thanks @madisongh !

Verified `jetson-xavier-nx-devkit-emmc` with nvme boot and initrd-flash works with `demo-image-base`, updated https://docs.google.com/spreadsheets/d/1EWG5QZvtWdk74gz48D4xCbegK-bsqMFJ8XOsyGdUUeI/edit?gid=1145771422#gid=1145771422

Will try swupdate/capsule update on this platform next.

**Comment by dwalkes** [comment]
Verified swupdate/capsule update on this config as well, added a row for this in https://docs.google.com/spreadsheets/d/1EWG5QZvtWdk74gz48D4xCbegK-bsqMFJ8XOsyGdUUeI/edit?gid=1145771422#gid=1145771422

**Comment by madisongh** [comment]
I've tested on an Orin Nano dev kit with an NVMe drive. I found an issue with a couple of the boot-related settings, which I've fixed. I updated the column in the spreadsheet to note the features I tested.

**Comment by dwalkes** [comment]
All docker tests passed on `demo-image-full` and `jetson-xavier-nx-devkit-emmc` with nvme boot after minor patch in https://github.com/OE4T/meta-tegra-community/pull/132.  I've updated the sheet.

**Comment by kekiefer** [comment]
I checked off a few things in the spreadsheet for AGX Xavier. No issues found there.

**Pull request merged**
