### PR TITLE
Updating the l4t_payload_updator patch to work with R32.7.1

### PR DESCRIPTION
**Pull request by MikeLoder**
The new Jetpack has updated the l4t_payload_updator script to be python3 compatible, however, it's not quite there yet. This patch updates some of the python3 issues as well as includes the changes for getting the board type by boardid and sku.

NOTE: Hoping to get this into the dunfell branch when you have the opportunity.

### CODE REVIEW

**Review by ichergui — APPROVED** [review]
LGTM

**Comment by MikeLoder** [comment]
I should have noted, that this fixes build breaks with the Nano, the current patch fails.

**Comment by ichergui** [comment]
> I should have noted, that this fixes build breaks with the Nano, the current patch fails.

Could you please create an issue attached to this PR and share logs ?

Thanks

**Comment by MikeLoder** [comment]
This PR fixes #974

**Comment by madisongh** [comment]
Thanks for the PR, @MikeLoder .  Could you please add a Signed-off-by line to the commit, per our [contribution guidelines](https://github.com/OE4T/meta-tegra/blob/master/CONTRIBUTING.md)?  Otherwise, LGTM

**Comment by MikeLoder** [comment]
I have added the Signed-off-by line thank you

**Review by madisongh — APPROVED** [review]

**Comment by madisongh** [comment]
I've backported this to the other 32.7.1-based branches.  Thanks!

**Comment by MikeLoder** [comment]
Thanks for the review and getting this in so quickly, really appreciate it.

**Pull request merged**
