### PR TITLE
at least typo in tegra-storage-layout-base_35.5.0.bb

### PR DESCRIPTION
**Pull request by tjhgit**
bug report [here](https://github.com/OE4T/meta-tegra/issues/1682)

### CODE REVIEW

**Comment by dwalkes** [comment]
Thanks @tjhgit however I think rather than changing the BSP layer for this mender specific issue it would probably be better to either:
1) Modify the mender layer to use the updated location in scarthgap (preferred) or
2) Put this change in a bbappend within the mender layer.

Note that I think scarthgap support for mender is still a work in progress, you may want to sync up with the PR at https://github.com/mendersoftware/meta-mender-community/pull/402

**Comment by tjhgit** [comment]
ok @dwalkes . But there is still the typo in the meta-tegra code: PARTITION_LAYOUT_EXERNAL . It is missing a T.

**Comment by dwalkes** [comment]
@tjhgit thank you I see that now.  Can you modify the commit to change only this single line?

**Comment by dwalkes** [comment]
You also need to sign off your commit per our [contributor guidelines](https://github.com/OE4T/meta-tegra/blob/master/CONTRIBUTING.md).

**Comment by tjhgit** [comment]
@dwalkes . Regarding changing the rest, I assume this would be here, right: ./meta-mender-tegra/recipes-bsp/tegra-binaries/tegra-storage-layout-base_%.bbappend ?

Sure will modify the commit to only the single line.

**Comment by dwalkes** [comment]
@tjhgit correct, although it looks like there should be handling for this already at https://github.com/mendersoftware/meta-mender-community/blob/scarthgap/meta-mender-tegra/recipes-bsp/tegra-binaries/tegra-storage-layout-base_%25.bbappend#L4

**Comment by dwalkes** [comment]
@tjhgit still missing signoff and you should squash your commits.  I can just propose a PR myself now that I understand the issue if you prefer.

**Comment by tjhgit** [comment]
@dwalkes . Sorry I am not so good at this ... I issued a git commit -s ... So kind to take over. Regarding: https://github.com/mendersoftware/meta-mender-community/blob/scarthgap/meta-mender-tegra/recipes-bsp/tegra-binaries/tegra-storage-layout-base_%25.bbappend#L4 , I think this function is using the wrong location: `mender_flash_layout_adjust()`.

**Comment by dwalkes** [comment]
> So kind that you offer to take over

No problem, thanks for reporting.  I've opened https://github.com/OE4T/meta-tegra/pull/1685

> I think this function is using the wrong location: do_install:append:tegra194()

Makes sense, so yes this is the change you could propose in that layer in a new PR.

**Pull request closed without merging**
