### PR TITLE
nvidia-docker l4t r35.4.1 changes

### PR DESCRIPTION
**Pull request by dwalkes**
Work in progress changes.  Building but not yet tested.

See related PR at https://github.com/OE4T/meta-tegra/pull/1310#issuecomment-1666995941 which will probably be needed for testing this.

### CODE REVIEW

**Comment by dwalkes** [comment]
Not able to complete container pulls in my first set of tests with jetson-xavier-nx-devkit-emmc, 60GB ROOTFSPART_SIZE and 37GB available in the rootfs, getting "no space left on device" pulling any container I've tried thus far.  It seems the extract step is taking 20+ GB for every container.  I don't remember seeing this previously.  Will retry with 120GB rootfs.

**Comment by dwalkes** [comment]
100 GB isn't enough either.  I can see the `/var/lib/docker/vfs/` directory is blowing up during the container pull.

I suspect this is because we are using the vfs storage driver for docker now for some reason instead of overlay2

```
root@jetson-xavier-nx-devkit-emmc:~# docker info | grep Storage
 Storage Driver: vfs
```

See https://docs.docker.com/storage/storagedriver/vfs-driver/

Not sure when this changed but I suspect after 35.3.1 based on the passing test in the [releases test spreadsheet](https://docs.google.com/spreadsheets/d/1EWG5QZvtWdk74gz48D4xCbegK-bsqMFJ8XOsyGdUUeI/edit#gid=1125662453) for this release.

**Comment by dwalkes** [comment]
From `journalctl -u docker`
```
Aug 13 04:44:00 jetson-xavier-nx-devkit-emmc dockerd[736]: time="2023-08-13T04:44:00.946986048Z" level=error msg="failed to mount overlay: no such device" storage-driver=overlay2
Aug 13 04:44:00 jetson-xavier-nx-devkit-emmc dockerd[736]: time="2023-08-13T04:44:00.947250798Z" level=error msg="exec: \"fuse-overlayfs\": executable file not found in $PATH" storage-driver=fu>
Aug 13 04:44:00 jetson-xavier-nx-devkit-emmc dockerd[736]: time="2023-08-13T04:44:00.947313880Z" level=error msg="Failed to built-in GetDriver graph btrfs /var/lib/docker"
Aug 13 04:44:00 jetson-xavier-nx-devkit-emmc dockerd[736]: time="2023-08-13T04:44:00.953155562Z" level=info msg="Loading containers: start."
```
It looks like the overlay module isn't ending up in the rootfs despite being enabled
```
root@jetson-xavier-nx-devkit-emmc:/# cat /proc/config.gz | gunzip | grep CONFIG_OVERLAY_FS
CONFIG_OVERLAY_FS=m
# CONFIG_OVERLAY_FS_REDIRECT_DIR is not set
# CONFIG_OVERLAY_FS_REDIRECT_ALWAYS_FOLLOW is not set
# CONFIG_OVERLAY_FS_INDEX is not set
# CONFIG_OVERLAY_FS_XINO_AUTO is not set
# CONFIG_OVERLAY_FS_METACOPY is not set
root@jetson-xavier-nx-devkit-emmc:/# find /lib/modules/ -name "overlay*"
root@jetson-xavier-nx-devkit-emmc:/# modprobe overlay
modprobe: FATAL: Module overlay not found in directory /lib/modules/5.10.120-l4t-r35.4.ga+g76678311c10b
root@jetson-xavier-nx-devkit-emmc:/#
```
Looks like it should be getting deployed to the rootfs based on the log for linux-tegra
```
dan@dan-tr:~/trellis/tegra-demo-distro/build-master-latest$ grep -r  "overlay" tmp/work/jetson_xavier_nx_devkit_emmc-oe4t-linux/linux-tegra/5.10*/temp/log.do_deploy
lib/modules/5.10.120-l4t-r35.4.ga+g76678311c10b/kernel/fs/overlayfs/
lib/modules/5.10.120-l4t-r35.4.ga+g76678311c10b/kernel/fs/overlayfs/overlay.ko
```

```
dan@dan-tr:~/trellis/tegra-demo-distro/build-master-latest$ find tmp/work/jetson_xavier_nx_devkit_emmc-oe4t-linux/linux-tegra/5.10*/ -name "overlay.ko"
tmp/work/jetson_xavier_nx_devkit_emmc-oe4t-linux/linux-tegra/5.10.120+gitAUTOINC+76678311c1-r0/package/lib/modules/5.10.120-l4t-r35.4.ga+g76678311c10b/kernel/fs/overlayfs/overlay.ko
tmp/work/jetson_xavier_nx_devkit_emmc-oe4t-linux/linux-tegra/5.10.120+gitAUTOINC+76678311c1-r0/package/lib/modules/5.10.120-l4t-r35.4.ga+g76678311c10b/kernel/fs/overlayfs/.debug/overlay.ko
tmp/work/jetson_xavier_nx_devkit_emmc-oe4t-linux/linux-tegra/5.10.120+gitAUTOINC+76678311c1-r0/packages-split/kernel-dbg/lib/modules/5.10.120-l4t-r35.4.ga+g76678311c10b/kernel/fs/overlayfs/.debug/overlay.ko
tmp/work/jetson_xavier_nx_devkit_emmc-oe4t-linux/linux-tegra/5.10.120+gitAUTOINC+76678311c1-r0/packages-split/kernel-module-overlay-5.10.120-l4t-r35.4.ga+g76678311c10b/lib/modules/5.10.120-l4t-r35.4.ga+g76678311c10b/kernel/fs/overlayfs/overlay.ko
tmp/work/jetson_xavier_nx_devkit_emmc-oe4t-linux/linux-tegra/5.10.120+gitAUTOINC+76678311c1-r0/linux-jetson_xavier_nx_devkit_emmc-standard-build/fs/overlayfs/overlay.ko
tmp/work/jetson_xavier_nx_devkit_emmc-oe4t-linux/linux-tegra/5.10.120+gitAUTOINC+76678311c1-r0/image/lib/modules/5.10.120-l4t-r35.4.ga+g76678311c10b/kernel/fs/overlayfs/overlay.ko
```
However it's not in the rootfs
```
dan@dan-tr:~/trellis/tegra-demo-distro/build-master-latest$ find tmp/work/jetson_xavier_nx_devkit_emmc-oe4t-linux/demo-image-full/1.0-r0/rootfs/lib/modules/5.10.120-l4t-r35.4.ga+g76678311c10b/kernel/fs
tmp/work/jetson_xavier_nx_devkit_emmc-oe4t-linux/demo-image-full/1.0-r0/rootfs/lib/modules/5.10.120-l4t-r35.4.ga+g76678311c10b/kernel/fs
tmp/work/jetson_xavier_nx_devkit_emmc-oe4t-linux/demo-image-full/1.0-r0/rootfs/lib/modules/5.10.120-l4t-r35.4.ga+g76678311c10b/kernel/fs/nls
tmp/work/jetson_xavier_nx_devkit_emmc-oe4t-linux/demo-image-full/1.0-r0/rootfs/lib/modules/5.10.120-l4t-r35.4.ga+g76678311c10b/kernel/fs/nls/nls_utf8.ko
tmp/work/jetson_xavier_nx_devkit_emmc-oe4t-linux/demo-image-full/1.0-r0/rootfs/lib/modules/5.10.120-l4t-r35.4.ga+g76678311c10b/kernel/fs/fuse
tmp/work/jetson_xavier_nx_devkit_emmc-oe4t-linux/demo-image-full/1.0-r0/rootfs/lib/modules/5.10.120-l4t-r35.4.ga+g76678311c10b/kernel/fs/fuse/fuse.ko
dan@dan-tr:~/trellis/tegra-demo-distro/build-master-latest$ find tmp/work/jetson_xavier_nx_devkit_emmc-oe4t-linux/demo-image-full/1.0-r0/rootfs/lib/modules/5.10.120-l4t-r35.4.ga+g76678311c10b/kernel/fs
tmp/work/jetson_xavier_nx_devkit_emmc-oe4t-linux/demo-image-full/1.0-r0/rootfs/lib/modules/5.10.120-l4t-r35.4.ga+g76678311c10b/kernel/fs
tmp/work/jetson_xavier_nx_devkit_emmc-oe4t-linux/demo-image-full/1.0-r0/rootfs/lib/modules/5.10.120-l4t-r35.4.ga+g76678311c10b/kernel/fs/nls
tmp/work/jetson_xavier_nx_devkit_emmc-oe4t-linux/demo-image-full/1.0-r0/rootfs/lib/modules/5.10.120-l4t-r35.4.ga+g76678311c10b/kernel/fs/nls/nls_utf8.ko
tmp/work/jetson_xavier_nx_devkit_emmc-oe4t-linux/demo-image-full/1.0-r0/rootfs/lib/modules/5.10.120-l4t-r35.4.ga+g76678311c10b/kernel/fs/fuse
tmp/work/jetson_xavier_nx_devkit_emmc-oe4t-linux/demo-image-full/1.0-r0/rootfs/lib/modules/5.10.120-l4t-r35.4.ga+g76678311c10b/kernel/fs/fuse/fuse.ko
```

**Comment by madisongh** [comment]
We list a bunch of kernel module dependencies in our [docker-ce bbappend](https://github.com/OE4T/meta-tegra/blob/937b449fb0756b39f61c1b815f37ebbbf2dc7ff9/external/virtualization-layer/recipes-containers/docker/docker-ce_%25.bbappend#L8-L23), but it looks like meta-virtualization master branch recently got a commit to [default to using docker-moby](https://git.yoctoproject.org/meta-virtualization/tree/conf/layer.conf#n44) instead of docker-ce.  So we probably need to create a bbappend for that recipe as well.

**Comment by madisongh** [comment]
@dwalkes  - Try rebasing this on the latest in the branch. The bbappend file now applied to `docker-moby`, and with that I was able to fire up the l4t-base r34.5.1 container in my latest demo-image-full build.

**Comment by dwalkes** [comment]
Thanks @madisongh.  Verified this works with `run-docker-tests` after https://github.com/OE4T/meta-tegra-community/pull/89.  The deepstream samples tests are failing for reasons I don't understand yet, however all containers are starting successfully.

**Pull request merged**
