### PR TITLE
initrd-flash: Add argument to format internal mmc partitions

### PR DESCRIPTION
**Pull request by quaresmajose**
- Preparation for adding support to flash wic images on external devices

### CODE REVIEW

**Comment by madisongh** [comment]
This seems like a too-specific addition to the script.  It might help if I could see more context around how this would enable use of wic for external devices (which might be relevant for #1323 as well).

Otherwise, I'd like to morph this into adding a generic mechanism for adding custom extensions to the initrd-flash process, maybe by installing extension scripts into a known location in the flashing initrd plus adding extension client-side script fragments into the tegraflash package that the initrd-flash script would automatically consume.  That way, if anyone has stuff they need to add to the flashing process for their specific needs, they can do that.

**Comment by quaresmajose** [comment]
Look like this is very aligned with our use case in the Linux microPlatform (LmP) as it is to solve possible issues when we do an over the air update after moving the rootfile system from the internal mmc to the external nvme. I sent this ones separately because it was easy to decouple from all other patches on the serie I have.

I agree with you that the better approach for this is adding support for installing extension scripts as well as script fragments into the tegraflash to control them. I plan to come back to this in the next few weeks to add the pending patches so can try to implement such feature too.

Thank you very much for your input, which is always very valuable.

**Comment by quaresmajose** [comment]
About the https://github.com/OE4T/meta-tegra/pull/1323: our implementation is to flash the wic on the nvme using the initrd flasher and using the tegra target to do that. We don't flash yet the nvme directly on the host machine for now.

**Comment by madisongh** [comment]
@quaresmajose Can you take a look at #1535 and see if the generic callout implemented there would work for you?

**Comment by quaresmajose** [comment]
> @quaresmajose Can you take a look at https://github.com/OE4T/meta-tegra/pull/1535 and see if the generic callout implemented there would work for you?

This solution sounds good, I will adapt my patch with this generic callout and will do some tests.

**Pull request closed without merging**
