### PR TITLE
Fix QA issue

### PR DESCRIPTION
**Pull request by ichergui**

### CODE REVIEW

**Review by madisongh — COMMENTED** [review]
I'm not sure about this.  Let me think about it.

**Comment by madisongh** [comment]
> This fixes my issues with deepstream-6.1

I understand, but the problem is really with how those DS libraries are linked.  Adding `file-rdeps` to INSANE_SKIP should also work.

Have you tried using the other intermediate packaging formats (`deb`, `ipk`)?  Does this RPROVIDES hackery work with them as well?

**Comment by ichergui** [comment]
> RPROVIDES

Adding the `file-rdeps` doesn't resolve the issue.
I didn't try other intermediate packaging formats.

**Comment by ichergui** [comment]
Close this PR because we have another solution

**Pull request closed without merging**
